### PR TITLE
开关顺序反了

### PR DESCRIPTION
**Pull request by ic0xgkk**
编译后发现开了没有日志输出，关了有输出了，IP地址也更新上了，看了看发现开关反了，修了修

### CODE REVIEW

**Comment by chenhw2** [comment]
I will check the init script.

This option should not be ```Disable```, it is counter-intuitive.

**Comment by ic0xgkk** [comment]
OK

**Comment by chenhw2** [comment]
try https://github.com/chenhw2/luci-app-aliddns/commit/0b86c7fb260c93c33754b352f611b2fa3b7f3ecd

**Comment by ic0xgkk** [comment]
OK，I will have a try today if i'm free.

**Pull request closed without merging**
